version: 2.1

orbs:
  win: circleci/windows@2.3.1

commands:
  install_yarn:
    steps:
      - restore_cache:
          keys:
            - yarn-packages-v3-{{ arch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v3-{{ arch }}-
      - run: yarn
  save_unix_yarn_cache:
    steps:
      - save_cache:
          key: yarn-packages-v3-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn/v6
  save_windows_yarn_cache:
    steps:
      - save_cache:
          key: yarn-packages-v3-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/AppData/Local/Yarn/Cache/v6

jobs:
  lint:
    docker:
      - image: node:12
    steps:
      - run: npm i -g yarn --force
      - run: yarn cache dir
      - checkout
      - install_yarn
      - save_unix_yarn_cache
      - run:
          name: prettier
          command: yarn prettier "*.js" "src/**/*" --check
      - run:
          name: eslint
          command: yarn lint
      - run:
          name: commitlint
          command: yarn commitlint --from master --to HEAD --verbose

  jest:
    docker:
      - image: node:12
    steps:
      - run: npm i -g yarn --force
      - run: yarn cache dir
      - checkout
      - install_yarn
      - save_unix_yarn_cache
      - run: yarn jest

  karma:
    executor: win/default
    steps:
      - run: npm i -g yarn --force
      - run: yarn cache dir
      - checkout
      - install_yarn
      - save_windows_yarn_cache
      - run: yarn karma:ie

  release:
    docker:
      - image: node:12
    steps:
      - run: npm i -g yarn --force
      - run: yarn cache dir
      - checkout
      - install_yarn
      - save_unix_yarn_cache
      - run: yarn build
      - run: yarn semantic-release

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - lint
      - jest
      - karma
      - release:
          requires:
            - lint
            - jest
            - karma
          filters:
            branches:
              only:
                - master
