version: 2.1
jobs:
  jest:
    docker:
      - image: node:12
    working_directory: ~/repository

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: npx lerna run jest
workflows:
  version: 2
  test:
    jobs:
      - jest
