version: 2.1
jobs:
  test:
    docker:
      - image: node:12
    working_directory: ~/repository

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn lint
      - run: npx lerna run jest

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
workflows:
  version: 2
  test:
    jobs:
      - test
