version: 2.1
orbs:
  win: circleci/windows@1.0.0

jobs:
  test-circleci:
    executor: win/vs2019
    steps:
      - checkout

  test:
    docker:
      - image: node:12
    working_directory: ~/repository

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn lint
      - run: yarn jest

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
workflows:
  version: 2
  test:
    jobs:
      - test-circleci
