name: test-and-release

on: [push]

jobs:
  lint-and-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn cache dir
      - name: Show versions
        run: |
          echo "node version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "yarn version: $(yarn -v)"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: yarn-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            yarn-v1-${{ runner.os }}-
      - run: yarn install
      - name: prettier
        run: yarn prettier "*.{js,json,ts,tsx,yml,md}" --check
      - name: eslint
        run: yarn lint
      - name: commitlint
        run: yarn commitlint --from origin/master --to HEAD --verbose
      - name: jest
        run: yarn jest
  karma-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn cache dir
      - name: Show versions
        run: |
          echo "node version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "yarn version: $(yarn -v)"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: yarn-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            yarn-v1-${{ runner.os }}-
      - run: yarn install
      - run: yarn karma:${{ matrix.browser }}
  karma-win:
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [ie]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn cache dir
      - name: Show versions
        run: |
          echo "node version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "yarn version: $(yarn -v)"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/AppData/Local/Yarn/Cache
          key: yarn-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            yarn-v1-${{ runner.os }}-
      - run: yarn install
      - run: yarn karma:${{ matrix.browser }}
  relese:
    needs: [lint-and-jest, karma-linux, karma-win]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn cache dir
      - name: Show versions
        run: |
          echo "node version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "yarn version: $(yarn -v)"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/AppData/Local/Yarn/Cache
          key: yarn-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            yarn-v1-${{ runner.os }}-
      - run: yarn install
      - run: yarn build
      - name: release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_WITH_WRITE_PERMISSION }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
